# remote_theme: pages-themes/modernist@v0.2.0
remote_theme: johno/pixyll
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ExBoard
description: The missing text-expansion keyboard for iOS
show_downloads: false
